name: Release

on:
  push:
    branches:
    - main
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v5
        id: release
        with:
          release-type: node
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@v7

      - name: Setup Bun
        if: ${{ steps.release.outputs.release_created }}
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        if: ${{ steps.release.outputs.release_created }}
        run: bun install

      - name: Build
        if: ${{ steps.release.outputs.release_created }}
        run: bun run build

      - name: Upload dist to release
        if: ${{ steps.release.outputs.release_created }}
        run: |
          gh release upload ${{ steps.release.outputs.tag_name }} dist/main.mjs dist/main.mjs.map
